import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { AlertTriangle, CheckCircle2, CircleCheck, Flag, Pencil, Plus, Repeat } from 'lucide-react'
import { format } from 'date-fns'
import { db } from '@/db/schema'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { EmptyState } from '@/components/shared/empty-state'
import type { MilestoneStatus } from '@/types/domain'
import { calculateMilestoneStatus, calculateScheduleHealth, calculateTaskProgress } from '@/lib/schedule-health'

const STATUS_CONFIG: Record<MilestoneStatus, { variant: 'success' | 'warning' | 'destructive'; icon: typeof Flag; label: string }> = { completed: { variant: 'success', icon: CheckCircle2, label: 'Completed' }, at_risk: { variant: 'warning', icon: AlertTriangle, label: 'At risk' }, delayed: { variant: 'destructive', icon: AlertTriangle, label: 'Delayed' }, on_track: { variant: 'success', icon: CircleCheck, label: 'On track' } }

export function MilestonesPanel({ projectId, canManage }: { projectId: string; canManage: boolean }) {
  const milestones = useLiveQuery(async () => (await db.milestones.where('projectId').equals(projectId).sortBy('dueDate')).map((milestone) => ({ ...milestone, startDate: milestone.startDate || milestone.dueDate })), [projectId])
  const progress = useLiveQuery(async () => { const [sprints, tasks] = await Promise.all([db.sprints.where('projectId').equals(projectId).toArray(), db.tasks.where('projectId').equals(projectId).toArray()]); return Object.fromEntries((milestones ?? []).map((milestone) => { const sprintIds = new Set(sprints.filter((sprint) => sprint.milestoneId === milestone.id).map((sprint) => sprint.id)); const related = tasks.filter((task) => task.milestoneId === milestone.id || (task.sprintId && sprintIds.has(task.sprintId))); return [milestone.id, { sprints: sprintIds.size, total: related.length, done: related.filter((task) => task.status === 'done').length, actualProgress: calculateTaskProgress(related) }] })) }, [projectId, milestones])
  const [open, setOpen] = useState(false), [editingId, setEditingId] = useState<string | null>(null), [name, setName] = useState(''), [startDate, setStartDate] = useState(''), [dueDate, setDueDate] = useState('')
  const reset = () => { setEditingId(null); setName(''); setStartDate(''); setDueDate('') }
  const openCreate = () => { reset(); setOpen(true) }
  function openEdit(milestone: { id: string; name: string; startDate: string; dueDate: string }) { setEditingId(milestone.id); setName(milestone.name); setStartDate(milestone.startDate.slice(0, 10)); setDueDate(milestone.dueDate.slice(0, 10)); setOpen(true) }
  async function save() { if (!name.trim() || !startDate || !dueDate || dueDate <= startDate) return; const values = { name: name.trim(), startDate: new Date(startDate).toISOString(), dueDate: new Date(dueDate).toISOString() }; if (editingId) await db.milestones.update(editingId, values); else await db.milestones.add({ id: crypto.randomUUID(), projectId, ...values, status: 'on_track' }); setOpen(false); reset() }
  return <div className="flex flex-1 flex-col gap-4 p-6">
    {canManage && <div className="flex justify-end"><Button size="sm" onClick={openCreate}><Plus aria-hidden="true" className="size-4" /> New milestone</Button></div>}
    {milestones?.length ? <div className="flex flex-col gap-3">{milestones.map((milestone) => { const item = progress?.[milestone.id]; const pct = item?.actualProgress ?? 0; const health = calculateScheduleHealth(milestone.startDate, milestone.dueDate, pct); const config = STATUS_CONFIG[calculateMilestoneStatus(item?.total ?? 0, pct, health)]; return <Card key={milestone.id}><CardContent className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-muted text-muted-foreground"><config.icon aria-hidden="true" className="size-4" /></div><div><p className="font-medium text-foreground">{milestone.name}</p><p className="text-xs text-muted-foreground">{format(new Date(milestone.startDate), 'MMM d, yyyy')} – {format(new Date(milestone.dueDate), 'MMM d, yyyy')}</p></div></div><div className="flex items-center gap-2"><Badge variant={config.variant}>{config.label}</Badge>{canManage && <Button size="sm" variant="outline" onClick={() => openEdit(milestone)}><Pencil aria-hidden="true" className="size-4" /> Edit</Button>}</div></CardContent><CardContent className="pt-0"><div className="mb-1.5 flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Repeat aria-hidden="true" className="size-3" /> {item?.sprints ?? 0} related sprint{item?.sprints === 1 ? '' : 's'}</span><span className="tabular-nums">Tasks {item?.done ?? 0}/{item?.total ?? 0} · Progress {pct}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted" aria-label={`Milestone progress: ${pct}%`}><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${pct}%` }} /></div>{health && <p className="mt-2 text-xs text-muted-foreground">Expected {health.expectedProgress}% · Actual {health.actualProgress}% · Delay {health.delayPercentage}%</p>}{!item?.total && <p className="mt-2 text-xs text-warning">No related tasks yet. Assign a task directly or link a sprint to measure delivery.</p>}</CardContent></Card> })}</div> : <EmptyState icon={Flag} title="No milestones yet" description="Mark the key dates this project needs to hit." actionLabel={canManage ? 'New milestone' : undefined} onAction={canManage ? openCreate : undefined} />}
    <Dialog open={open} onOpenChange={(next) => { setOpen(next); if (!next) reset() }}><DialogContent><DialogHeader><DialogTitle>{editingId ? 'Edit milestone' : 'New milestone'}</DialogTitle></DialogHeader><div className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="ms-name">Name</Label><Input id="ms-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Public launch" /></div><div className="flex flex-col gap-2"><Label htmlFor="ms-start">Start date</Label><Input id="ms-start" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="ms-date">Due date</Label><Input id="ms-date" type="date" min={startDate} value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save} disabled={!name.trim() || !startDate || !dueDate || dueDate <= startDate}>{editingId ? 'Save changes' : 'Create milestone'}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
