import { ClipboardPlus, Crown, Eye, Route, Plus, Trash2, ChevronDown, ChevronUp } from 'lucide-react'
import { db } from '@/db/schema'
import { useLiveQuery } from 'dexie-react-hooks'
import type { Project, ProjectStatus, User, WorkflowStage, WorkspaceTerminology } from '@/types/domain'
import { DEFAULT_TERMINOLOGY, workflowStages } from '@/lib/project-workflow'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

const PROJECT_STATUS_LABELS: Record<ProjectStatus, string> = { planning: 'Planning', active: 'Active', on_hold: 'On hold', completed: 'Completed', archived: 'Archived' }
const memberName = (members: User[], id?: string) => members.find((member) => member.id === id)?.name ?? 'Not assigned'

export function ProjectOperatingModel({ project, members, canManage, section = 'all' }: { project: Project; members: User[]; canManage: boolean; section?: 'all' | 'workflow' | 'responsibilities' | 'terminology' }) {
  const stages = workflowStages(project)
  const terminology = project.terminology ?? DEFAULT_TERMINOLOGY
  const teams = useLiveQuery(() => db.teams.where('orgId').equals(project.orgId).toArray(), [project.orgId])
  const update = (next: WorkflowStage[]) => void db.projects.update(project.id, { workflowStages: next, workflowSetId: undefined })
  const patch = (id: string, fields: Partial<WorkflowStage>) => update(stages.map((stage) => stage.id === id ? { ...stage, ...fields } : stage))
  const move = (index: number, delta: -1 | 1) => { const next = [...stages]; const to = index + delta; if (next[to]) [next[index], next[to]] = [next[to], next[index]]; update(next) }
  const roles = [{ field: 'leadId' as const, icon: Crown, label: 'Project manager', help: 'Accountable for the project outcome.' }, { field: 'coordinatorId' as const, icon: ClipboardPlus, label: 'Work coordinator', help: 'Defines and prioritizes work.' }, { field: 'reviewerId' as const, icon: Eye, label: 'Default reviewer', help: 'Fallback when a review stage has no named reviewers.' }]
  const patchTerminology = (field: keyof WorkspaceTerminology, value: string) => void db.projects.update(project.id, { terminology: { ...terminology, [field]: value || terminology[field] }, workflowSetId: undefined })
  return <div className={`grid gap-6 ${section === 'all' ? 'xl:grid-cols-2' : ''}`}>
    {section !== 'workflow' && section !== 'terminology' && <Card><CardHeader><CardTitle>Project responsibilities</CardTitle></CardHeader><CardContent className="flex flex-col gap-4">
      {roles.map(({ field, icon: Icon, label, help }) => <div key={field} className="grid gap-2 rounded-lg border border-border p-3 sm:grid-cols-[1fr_220px] sm:items-center"><div className="flex gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4" /></div><div><Label>{label}</Label><p className="text-xs text-muted-foreground">{help}</p></div></div>{canManage ? <Select value={project[field] ?? 'unassigned'} onValueChange={(value) => { const next = value === 'unassigned' ? undefined : value; if (field === 'leadId') void db.projects.update(project.id, { leadId: next }); else if (field === 'coordinatorId') void db.projects.update(project.id, { coordinatorId: next }); else void db.projects.update(project.id, { reviewerId: next }) }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="unassigned">Not assigned</SelectItem>{members.map((member) => <SelectItem key={member.id} value={member.id}>{member.name}</SelectItem>)}</SelectContent></Select> : <p className="text-sm font-medium">{memberName(members, project[field])}</p>}</div>)}
      <div className="border-t pt-4"><Label>Reported project status</Label><Select disabled={!canManage} value={project.status} onValueChange={(value) => void db.projects.update(project.id, { status: value as ProjectStatus })}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(PROJECT_STATUS_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>
    </CardContent></Card>}
    {section !== 'responsibilities' && section !== 'terminology' && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Route aria-hidden="true" className="size-4 text-primary" /> Project workflow</CardTitle><p className="text-sm text-muted-foreground">Create a workflow set for this project: add, rename, reorder, or remove stages and set their review rules.</p></CardHeader><CardContent className="flex flex-col gap-3">
      {stages.map((stage, index) => <div key={stage.id} className="rounded-xl border border-border p-3"><div className="flex gap-2"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row">{canManage ? <Input className="min-w-0 flex-1" value={stage.name} onChange={(e) => patch(stage.id, { name: e.target.value || stage.name })} aria-label={`Stage ${index + 1} name`} /> : <p className="py-2 text-sm font-medium">{stage.name}</p>}{canManage && <div className="flex shrink-0"><Button size="icon" variant="ghost" aria-label={`Move ${stage.name} up`} disabled={!index} onClick={() => move(index, -1)}><ChevronUp aria-hidden="true" className="size-4" /></Button><Button size="icon" variant="ghost" aria-label={`Move ${stage.name} down`} disabled={index === stages.length - 1} onClick={() => move(index, 1)}><ChevronDown aria-hidden="true" className="size-4" /></Button><Button size="icon" variant="ghost" aria-label={`Delete ${stage.name}`} disabled={stages.length === 1} onClick={() => update(stages.filter((item) => item.id !== stage.id))}><Trash2 aria-hidden="true" className="size-4 text-destructive" /></Button></div>}</div>
        {canManage && <><Input className="mt-2" value={stage.description ?? ''} onChange={(e) => patch(stage.id, { description: e.target.value || undefined })} placeholder="Description" /><Input className="mt-2" value={stage.rules ?? ''} onChange={(e) => patch(stage.id, { rules: e.target.value || undefined })} placeholder="Rule or exit criteria" /></>}
        <div className="mt-3 flex items-center gap-2"><Switch id={`stage-review-${stage.id}`} disabled={!canManage} checked={Boolean(stage.requiresReview)} onCheckedChange={(value) => patch(stage.id, { requiresReview: value })} /><Label htmlFor={`stage-review-${stage.id}`} className="text-xs text-muted-foreground">Review required</Label></div>
        {stage.requiresReview && <div className="mt-2 rounded-lg bg-muted/50 p-2"><p className="flex items-center gap-1 text-xs font-medium text-muted-foreground"><Eye className="size-3.5" /> Assigned reviewers {stage.reviewerIds?.length || stage.reviewerTeamIds?.length ? `(${(stage.reviewerIds?.length ?? 0) + (stage.reviewerTeamIds?.length ?? 0)})` : '— default reviewer applies'}</p>{canManage && <><div className="mt-2 grid gap-1 sm:grid-cols-2">{members.map((member) => { const checked = stage.reviewerIds?.includes(member.id) ?? false; return <label key={member.id} className="flex items-center gap-2 text-xs"><Checkbox checked={checked} onCheckedChange={(value) => patch(stage.id, { reviewerIds: value ? [...(stage.reviewerIds ?? []), member.id] : (stage.reviewerIds ?? []).filter((id) => id !== member.id) })} />{member.name}</label> })}</div>{teams && teams.length > 0 && <div className="mt-2 border-t pt-2"><p className="text-xs font-medium text-muted-foreground">Reviewer teams</p><div className="mt-1 grid gap-1 sm:grid-cols-2">{teams.map((team) => { const checked = stage.reviewerTeamIds?.includes(team.id) ?? false; return <label key={team.id} className="flex items-center gap-2 text-xs"><Checkbox checked={checked} onCheckedChange={(value) => patch(stage.id, { reviewerTeamIds: value ? [...(stage.reviewerTeamIds ?? []), team.id] : (stage.reviewerTeamIds ?? []).filter((id) => id !== team.id) })} />{team.name}</label> })}</div></div>}</>}</div>}
      </div></div></div>)}
      {canManage && <Button variant="outline" onClick={() => update([...stages, { id: `stage-${crypto.randomUUID()}`, name: 'New stage' }])}><Plus aria-hidden="true" className="size-4" /> Add workflow stage</Button>}
    </CardContent></Card>}
    {section !== 'workflow' && section !== 'responsibilities' && <Card><CardHeader><CardTitle>Project terminology</CardTitle><p className="text-sm text-muted-foreground">Use the language your team and stakeholders already use. This only changes labels, not your data.</p></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">
      {([['workItem', 'Work item'], ['workItemPlural', 'Work items'], ['timebox', 'Timebox'], ['timeboxPlural', 'Timeboxes'], ['milestone', 'Milestone'], ['milestonePlural', 'Milestones'], ['issue', 'Issue'], ['release', 'Release update']] as [keyof WorkspaceTerminology, string][]).map(([field, label]) => <div key={field} className="flex flex-col gap-1.5"><Label htmlFor={`terminology-${field}`}>{label}</Label>{canManage ? <Input id={`terminology-${field}`} value={terminology[field]} onChange={(event) => patchTerminology(field, event.target.value)} /> : <p className="text-sm font-medium">{terminology[field]}</p>}</div>)}
    </CardContent></Card>}
  </div>
}
