import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { Flag, Pencil, Plus, Repeat } from 'lucide-react'
import { addDays, format } from 'date-fns'
import { db } from '@/db/schema'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { EmptyState } from '@/components/shared/empty-state'
import type { SprintStatus, WorkspaceTerminology } from '@/types/domain'
import { calculateScheduleHealth, calculateTaskProgress, SCHEDULE_HEALTH_LABEL, SCHEDULE_HEALTH_VARIANT } from '@/lib/schedule-health'

const STATUS_VARIANT: Record<SprintStatus, 'success' | 'secondary' | 'outline'> = { active: 'success', planned: 'secondary', completed: 'outline' }
const toLocalDateTime = (date: Date) => format(date, "yyyy-MM-dd'T'HH:mm")

export function SprintsPanel({ projectId, terminology, canManage }: { projectId: string; terminology: WorkspaceTerminology; canManage: boolean }) {
  const sprints = useLiveQuery(() => db.sprints.where('projectId').equals(projectId).toArray(), [projectId])
  const milestones = useLiveQuery(() => db.milestones.where('projectId').equals(projectId).sortBy('dueDate'), [projectId])
  const taskCounts = useLiveQuery(async () => { const tasks = await db.tasks.where('projectId').equals(projectId).toArray(); const counts: Record<string, { total: number; done: number; progress: number }> = {}; for (const task of tasks) if (task.sprintId) { counts[task.sprintId] ??= { total: 0, done: 0, progress: 0 }; counts[task.sprintId].total += 1; if (task.status === 'done') counts[task.sprintId].done += 1 }; for (const [sprintId, count] of Object.entries(counts)) count.progress = calculateTaskProgress(tasks.filter((task) => task.sprintId === sprintId)); return counts }, [projectId, sprints])
  const [open, setOpen] = useState(false), [editingId, setEditingId] = useState<string | null>(null), [name, setName] = useState(''), [goal, setGoal] = useState(''), [milestoneId, setMilestoneId] = useState('none'), [status, setStatus] = useState<SprintStatus>('planned')
  const [startDate, setStartDate] = useState(() => toLocalDateTime(new Date())), [endDate, setEndDate] = useState(() => toLocalDateTime(addDays(new Date(), 14)))
  const reset = () => { setEditingId(null); setName(''); setGoal(''); setMilestoneId('none'); setStatus('planned'); setStartDate(toLocalDateTime(new Date())); setEndDate(toLocalDateTime(addDays(new Date(), 14))) }
  const openCreate = () => { reset(); setOpen(true) }
  function openEdit(sprint: { id: string; name: string; goal?: string; milestoneId?: string; startDate: string; endDate: string; status: SprintStatus }) { setEditingId(sprint.id); setName(sprint.name); setGoal(sprint.goal ?? ''); setMilestoneId(sprint.milestoneId ?? 'none'); setStatus(sprint.status); setStartDate(toLocalDateTime(new Date(sprint.startDate))); setEndDate(toLocalDateTime(new Date(sprint.endDate))); setOpen(true) }
  async function save() { if (!name.trim() || !startDate || !endDate || new Date(endDate) <= new Date(startDate)) return; const values = { name: name.trim(), goal: goal.trim() || undefined, milestoneId: milestoneId === 'none' ? undefined : milestoneId, startDate: new Date(startDate).toISOString(), endDate: new Date(endDate).toISOString(), status }; if (editingId) await db.sprints.update(editingId, values); else await db.sprints.add({ id: crypto.randomUUID(), projectId, ...values }); setOpen(false); reset() }
  async function advanceSprint(id: string, nextStatus: SprintStatus) { await db.sprints.update(id, { status: nextStatus }) }
  return <div className="flex flex-1 flex-col gap-4 p-6">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/15 bg-primary/5 p-4"><div><p className="text-sm font-semibold text-foreground">Plan from outcomes, not disconnected work</p><p className="text-xs text-muted-foreground">Create a {terminology.milestone.toLowerCase()}, link a {terminology.timebox.toLowerCase()} to it, then commit {terminology.workItemPlural.toLowerCase()}.</p></div>{canManage && <Button size="sm" onClick={openCreate}><Plus aria-hidden="true" className="size-4" /> New {terminology.timebox.toLowerCase()}</Button>}</div>
    {sprints?.length ? <div className="flex flex-col gap-3">{sprints.map((sprint) => { const counts = taskCounts?.[sprint.id]; const milestone = milestones?.find((item) => item.id === sprint.milestoneId); const pct = counts?.progress ?? 0; const health = calculateScheduleHealth(sprint.startDate, sprint.endDate, pct); return <Card key={sprint.id}><CardHeader className="flex-row items-center justify-between space-y-0"><CardTitle className="flex items-center gap-2 text-base"><Repeat aria-hidden="true" className="size-4 text-muted-foreground" />{sprint.name}</CardTitle><div className="flex flex-wrap justify-end gap-1.5"><Badge variant={STATUS_VARIANT[sprint.status]}>{sprint.status}</Badge>{sprint.status !== 'completed' && health && <Badge variant={SCHEDULE_HEALTH_VARIANT[health.status]}>{health.delayPercentage ? `${health.delayPercentage}% behind schedule` : SCHEDULE_HEALTH_LABEL[health.status]}</Badge>}</div></CardHeader><CardContent className="flex flex-col gap-3">{sprint.goal && <p className="text-sm text-muted-foreground">{sprint.goal}</p>}<p className="flex items-center gap-1.5 text-xs text-muted-foreground"><Flag aria-hidden="true" className="size-3.5" />{milestone ? <>Contributes to <span className="font-medium text-foreground">{milestone.name}</span></> : <span className="text-warning">No milestone linked — link one to measure outcome progress.</span>}</p><p className="text-xs text-muted-foreground">{format(new Date(sprint.startDate), 'MMM d, yyyy · p')} – {format(new Date(sprint.endDate), 'MMM d, yyyy · p')}</p><div className="flex items-center gap-3" aria-label={`Sprint progress: ${pct}%`}><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${pct}%` }} /></div><span className="text-xs font-medium tabular-nums text-muted-foreground">Progress {pct}% · Tasks {counts?.done ?? 0}/{counts?.total ?? 0}</span></div>{health && <p className="text-xs text-muted-foreground">Expected {health.expectedProgress}% · Actual {health.actualProgress}% · Delay {health.delayPercentage}%</p>}{canManage && <div className="flex flex-wrap justify-end gap-2"><Button size="sm" variant="outline" onClick={() => openEdit(sprint)}><Pencil aria-hidden="true" className="size-4" /> Edit</Button>{sprint.status !== 'completed' && <Button size="sm" variant={sprint.status === 'planned' ? 'default' : 'outline'} onClick={() => advanceSprint(sprint.id, sprint.status === 'planned' ? 'active' : 'completed')}>{sprint.status === 'planned' ? 'Start sprint' : 'Complete sprint'}</Button>}</div>}</CardContent></Card> })}</div> : <EmptyState icon={Repeat} title="No sprints yet" description="Create a sprint to start planning work in time-boxed cycles." actionLabel={canManage ? 'New sprint' : undefined} onAction={canManage ? openCreate : undefined} />}
    <Dialog open={open} onOpenChange={(next) => { setOpen(next); if (!next) reset() }}><DialogContent><DialogHeader><DialogTitle>{editingId ? 'Edit sprint' : 'New sprint'}</DialogTitle></DialogHeader><div className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="sprint-name">Name</Label><Input id="sprint-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Sprint 5" /></div><div className="flex flex-col gap-2"><Label htmlFor="sprint-goal">Goal</Label><Input id="sprint-goal" value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="Optional" /></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label htmlFor="sprint-start">Start date and time</Label><Input id="sprint-start" type="datetime-local" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="sprint-end">Due date and time</Label><Input id="sprint-end" type="datetime-local" min={startDate} value={endDate} onChange={(event) => setEndDate(event.target.value)} /></div></div><div className="flex flex-col gap-2"><Label htmlFor="sprint-milestone">Milestone</Label><select id="sprint-milestone" value={milestoneId} onChange={(event) => setMilestoneId(event.target.value)} className="h-10 rounded-md border border-border bg-background px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"><option value="none">Link later</option>{milestones?.map((milestone) => <option key={milestone.id} value={milestone.id}>{milestone.name}</option>)}</select><p className="text-xs text-muted-foreground">A milestone makes this sprint’s delivery measurable.</p></div>{editingId && <div className="flex flex-col gap-2"><Label htmlFor="sprint-status">Status</Label><select id="sprint-status" value={status} onChange={(event) => setStatus(event.target.value as SprintStatus)} className="h-10 rounded-md border border-border bg-background px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"><option value="planned">Planned</option><option value="active">Active</option><option value="completed">Completed</option></select></div>}</div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save} disabled={!name.trim() || !startDate || !endDate || new Date(endDate) <= new Date(startDate)}>{editingId ? 'Save changes' : 'Create sprint'}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
