import { expect, test } from '@playwright/test'

test('guided onboarding navigates the delivery flow and creates a real task', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/register')
  await page.getByLabel('Full name').fill('Tutorial Owner')
  await page.getByLabel('Email address').fill('tutorial-owner@connectio.test')
  await page.getByLabel('Password', { exact: true }).fill('Tutorial!2026')
  await page.getByLabel('Confirm password').fill('Tutorial!2026')
  await page.getByRole('button', { name: 'Create account' }).click()

  const verificationCode = await page.locator('strong.font-mono').textContent()
  await page.getByLabel('Verification code').fill(verificationCode ?? '')
  await page.getByRole('button', { name: 'Verify email' }).click()
  await page.locator('#login-password').fill('Tutorial!2026')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await page.getByLabel('Organization name').fill('Tutorial Studio')
  await page.getByRole('button', { name: 'Create organization' }).click()
  await page.getByRole('button', { name: 'Select Free' }).click()
  await page.getByLabel('Workspace name').fill('Product Delivery')
  await page.getByRole('button', { name: 'Create workspace' }).click()
  await page.getByRole('button', { name: 'Skip for now' }).click()

  const tour = page.getByRole('dialog', { name: /Create your first task/ })
  await expect(tour).toBeVisible()
  await tour.getByRole('button', { name: 'Start tutorial' }).click()

  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible()
  await page.getByRole('button', { name: 'Explore workspaces' }).click()
  await expect(page.getByRole('heading', { name: 'Workspaces', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Open workspace' }).click()
  await expect(page.getByText('Getting started', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Open project' }).click()
  await expect(page.getByRole('tab', { name: 'Board' })).toBeVisible()
  await page.getByRole('button', { name: 'See sprint planning' }).click()
  await expect(page.getByText('Getting started sprint', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Go to the board' }).click()
  await expect(page.getByRole('button', { name: 'Create a task' })).toBeVisible()
  await page.getByRole('button', { name: 'Create a task' }).click()

  await page.getByRole('button', { name: 'Add task' }).click()
  await page.locator('[data-tour="task-title"]').fill('Publish onboarding checklist')
  await page.locator('[data-tour="task-title"]').press('Enter')
  await expect(page.getByText('Your task is live on the board')).toBeVisible()
  await page.getByRole('button', { name: 'Open task details' }).click()

  await expect(page.locator('[data-tour="task-detail"]')).toBeVisible()
  await page.getByRole('button', { name: 'Finish tutorial' }).click()
  await expect(page.getByText('You’re ready to deliver')).toBeVisible()
  await page.getByRole('button', { name: 'Done' }).click()
  await expect(page.getByText('You’re ready to deliver')).toBeHidden()
  await expect(page.locator('[data-tour-task]').filter({ hasText: 'Publish onboarding checklist' })).toBeVisible()

  await page.getByRole('button', { name: 'Start guided tutorial' }).click()
  await page.setViewportSize({ width: 375, height: 812 })
  await expect(tour).toBeVisible()
  const bounds = await tour.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(375)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(812)
  await tour.getByRole('button', { name: 'Skip tour', exact: true }).click()
})
